export const countryToFlag = (isoCode) => {
  return isoCode
    .split('')
    .map(char => String.fromCodePoint(0x1F1E6 + char.charCodeAt(0) - 65))
    .join('');
}

export const countries = {
  AF: { name: "Afghanistan", continent: "asia", flag: countryToFlag("AF") },
  AL: { name: "Albania", continent: "europe", flag: countryToFlag("AL") },
  DZ: { name: "Algeria", continent: "africa", flag: countryToFlag("DZ") },
  AD: { name: "Andorra", continent: "europe", flag: countryToFlag("AD") },
  AO: { name: "Angola", continent: "africa", flag: countryToFlag("AO") },
  AG: { name: "Antigua and Barbuda", continent: "north-america", flag: countryToFlag("AG") },
  AR: { name: "Argentina", continent: "south-america", flag: countryToFlag("AR") },
  AM: { name: "Armenia", continent: "asia", flag: countryToFlag("AM") },
  AU: { name: "Australia", continent: "oceania", flag: countryToFlag("AU") },
  AT: { name: "Austria", continent: "europe", flag: countryToFlag("AT") },
  AZ: { name: "Azerbaijan", continent: "asia", flag: countryToFlag("AZ") },

  BS: { name: "Bahamas", continent: "north-america", flag: countryToFlag("BS") },
  BH: { name: "Bahrain", continent: "asia", flag: countryToFlag("BH") },
  BD: { name: "Bangladesh", continent: "asia", flag: countryToFlag("BD") },
  BB: { name: "Barbados", continent: "north-america", flag: countryToFlag("BB") },
  BY: { name: "Belarus", continent: "europe", flag: countryToFlag("BY") },
  BE: { name: "Belgium", continent: "europe", flag: countryToFlag("BE") },
  BZ: { name: "Belize", continent: "north-america", flag: countryToFlag("BZ") },
  BJ: { name: "Benin", continent: "africa", flag: countryToFlag("BJ") },
  BT: { name: "Bhutan", continent: "asia", flag: countryToFlag("BT") },
  BO: { name: "Bolivia", continent: "south-america", flag: countryToFlag("BO") },
  BA: { name: "Bosnia and Herzegovina", continent: "europe", flag: countryToFlag("BA") },
  BW: { name: "Botswana", continent: "africa", flag: countryToFlag("BW") },
  BR: { name: "Brazil", continent: "south-america", flag: countryToFlag("BR") },
  BN: { name: "Brunei", continent: "asia", flag: countryToFlag("BN") },
  BG: { name: "Bulgaria", continent: "europe", flag: countryToFlag("BG") },
  BF: { name: "Burkina Faso", continent: "africa", flag: countryToFlag("BF") },
  BI: { name: "Burundi", continent: "africa", flag: countryToFlag("BI") },

  KH: { name: "Cambodia", continent: "asia", flag: countryToFlag("KH") },
  CM: { name: "Cameroon", continent: "africa", flag: countryToFlag("CM") },
  CA: { name: "Canada", continent: "north-america", flag: countryToFlag("CA") },
  CV: { name: "Cape Verde", continent: "africa", flag: countryToFlag("CV") },
  CF: { name: "Central African Republic", continent: "africa", flag: countryToFlag("CF") },
  TD: { name: "Chad", continent: "africa", flag: countryToFlag("TD") },
  CL: { name: "Chile", continent: "south-america", flag: countryToFlag("CL") },
  CN: { name: "China", continent: "asia", flag: countryToFlag("CN") },
  CO: { name: "Colombia", continent: "south-america", flag: countryToFlag("CO") },
  KM: { name: "Comoros", continent: "africa", flag: countryToFlag("KM") },
  CR: { name: "Costa Rica", continent: "north-america", flag: countryToFlag("CR") },
  CI: { name: "Côte d’Ivoire", continent: "africa", flag: countryToFlag("CI") },
  HR: { name: "Croatia", continent: "europe", flag: countryToFlag("HR") },
  CU: { name: "Cuba", continent: "north-america", flag: countryToFlag("CU") },
  CY: { name: "Cyprus", continent: "asia", flag: countryToFlag("CY") },
  CZ: { name: "Czech Republic", continent: "europe", flag: countryToFlag("CZ") },

  DK: { name: "Denmark", continent: "europe", flag: countryToFlag("DK") },
  DJ: { name: "Djibouti", continent: "africa", flag: countryToFlag("DJ") },
  DM: { name: "Dominica", continent: "north-america", flag: countryToFlag("DM") },
  DO: { name: "Dominican Republic", continent: "north-america", flag: countryToFlag("DO") },

  EC: { name: "Ecuador", continent: "south-america", flag: countryToFlag("EC") },
  EG: { name: "Egypt", continent: "africa", flag: countryToFlag("EG") },
  SV: { name: "El Salvador", continent: "north-america", flag: countryToFlag("SV") },
  GQ: { name: "Equatorial Guinea", continent: "africa", flag: countryToFlag("GQ") },
  ER: { name: "Eritrea", continent: "africa", flag: countryToFlag("ER") },
  EE: { name: "Estonia", continent: "europe", flag: countryToFlag("EE") },
  SZ: { name: "Eswatini", continent: "africa", flag: countryToFlag("SZ") },
  ET: { name: "Ethiopia", continent: "africa", flag: countryToFlag("ET") },

  FI: { name: "Finland", continent: "europe", flag: countryToFlag("FI") },
  FR: { name: "France", continent: "europe", flag: countryToFlag("FR") },

  GA: { name: "Gabon", continent: "africa", flag: countryToFlag("GA") },
  GM: { name: "Gambia", continent: "africa", flag: countryToFlag("GM") },
  GE: { name: "Georgia", continent: "asia", flag: countryToFlag("GE") },
  DE: { name: "Germany", continent: "europe", flag: countryToFlag("DE") },
  GH: { name: "Ghana", continent: "africa", flag: countryToFlag("GH") },
  GR: { name: "Greece", continent: "europe", flag: countryToFlag("GR") },
  GD: { name: "Grenada", continent: "north-america", flag: countryToFlag("GD") },
  GT: { name: "Guatemala", continent: "north-america", flag: countryToFlag("GT") },
  GN: { name: "Guinea", continent: "africa", flag: countryToFlag("GN") },
  GW: { name: "Guinea-Bissau", continent: "africa", flag: countryToFlag("GW") },
  GY: { name: "Guyana", continent: "south-america", flag: countryToFlag("GY") },

  HT: { name: "Haiti", continent: "north-america", flag: countryToFlag("HT") },
  HN: { name: "Honduras", continent: "north-america", flag: countryToFlag("HN") },
  HU: { name: "Hungary", continent: "europe", flag: countryToFlag("HU") },

  IS: { name: "Iceland", continent: "europe", flag: countryToFlag("IS") },
  IN: { name: "India", continent: "asia", flag: countryToFlag("IN") },
  ID: { name: "Indonesia", continent: "asia", flag: countryToFlag("ID") },
  IR: { name: "Iran", continent: "asia", flag: countryToFlag("IR") },
  IQ: { name: "Iraq", continent: "asia", flag: countryToFlag("IQ") },
  IE: { name: "Ireland", continent: "europe", flag: countryToFlag("IE") },
  IL: { name: "Israel", continent: "asia", flag: countryToFlag("IL") },
  IT: { name: "Italy", continent: "europe", flag: countryToFlag("IT") },

  JM: { name: "Jamaica", continent: "north-america", flag: countryToFlag("JM") },
  JP: { name: "Japan", continent: "asia", flag: countryToFlag("JP") },
  JO: { name: "Jordan", continent: "asia", flag: countryToFlag("JO") },

  KZ: { name: "Kazakhstan", continent: "asia", flag: countryToFlag("KZ") },
  KE: { name: "Kenya", continent: "africa", flag: countryToFlag("KE") },
  KI: { name: "Kiribati", continent: "oceania", flag: countryToFlag("KI") },
  KW: { name: "Kuwait", continent: "asia", flag: countryToFlag("KW") },
  KG: { name: "Kyrgyzstan", continent: "asia", flag: countryToFlag("KG") },

  LA: { name: "Laos", continent: "asia", flag: countryToFlag("LA") },
  LV: { name: "Latvia", continent: "europe", flag: countryToFlag("LV") },
  LB: { name: "Lebanon", continent: "asia", flag: countryToFlag("LB") },
  LS: { name: "Lesotho", continent: "africa", flag: countryToFlag("LS") },
  LR: { name: "Liberia", continent: "africa", flag: countryToFlag("LR") },
  LY: { name: "Libya", continent: "africa", flag: countryToFlag("LY") },
  LI: { name: "Liechtenstein", continent: "europe", flag: countryToFlag("LI") },
  LT: { name: "Lithuania", continent: "europe", flag: countryToFlag("LT") },
  LU: { name: "Luxembourg", continent: "europe", flag: countryToFlag("LU") },

  MG: { name: "Madagascar", continent: "africa", flag: countryToFlag("MG") },
  MW: { name: "Malawi", continent: "africa", flag: countryToFlag("MW") },
  MY: { name: "Malaysia", continent: "asia", flag: countryToFlag("MY") },
  MV: { name: "Maldives", continent: "asia", flag: countryToFlag("MV") },
  ML: { name: "Mali", continent: "africa", flag: countryToFlag("ML") },
  MT: { name: "Malta", continent: "europe", flag: countryToFlag("MT") },
  MH: { name: "Marshall Islands", continent: "oceania", flag: countryToFlag("MH") },
  MR: { name: "Mauritania", continent: "africa", flag: countryToFlag("MR") },
  MU: { name: "Mauritius", continent: "africa", flag: countryToFlag("MU") },
  MX: { name: "Mexico", continent: "north-america", flag: countryToFlag("MX") },
  FM: { name: "Micronesia", continent: "oceania", flag: countryToFlag("FM") },
  MD: { name: "Moldova", continent: "europe", flag: countryToFlag("MD") },
  MC: { name: "Monaco", continent: "europe", flag: countryToFlag("MC") },
  MN: { name: "Mongolia", continent: "asia", flag: countryToFlag("MN") },
  ME: { name: "Montenegro", continent: "europe", flag: countryToFlag("ME") },
  MA: { name: "Morocco", continent: "africa", flag: countryToFlag("MA") },
  MZ: { name: "Mozambique", continent: "africa", flag: countryToFlag("MZ") },
  MM: { name: "Myanmar", continent: "asia", flag: countryToFlag("MM") },

  NA: { name: "Namibia", continent: "africa", flag: countryToFlag("NA") },
  NR: { name: "Nauru", continent: "oceania", flag: countryToFlag("NR") },
  NP: { name: "Nepal", continent: "asia", flag: countryToFlag("NP") },
  NL: { name: "Netherlands", continent: "europe", flag: countryToFlag("NL") },
  NZ: { name: "New Zealand", continent: "oceania", flag: countryToFlag("NZ") },
  NI: { name: "Nicaragua", continent: "north-america", flag: countryToFlag("NI") },
  NE: { name: "Niger", continent: "africa", flag: countryToFlag("NE") },
  NG: { name: "Nigeria", continent: "africa", flag: countryToFlag("NG") },
  KP: { name: "North Korea", continent: "asia", flag: countryToFlag("KP") },
  MK: { name: "North Macedonia", continent: "europe", flag: countryToFlag("MK") },
  NO: { name: "Norway", continent: "europe", flag: countryToFlag("NO") },

  OM: { name: "Oman", continent: "asia", flag: countryToFlag("OM") },

  PK: { name: "Pakistan", continent: "asia", flag: countryToFlag("PK") },
  PW: { name: "Palau", continent: "oceania", flag: countryToFlag("PW") },
  PA: { name: "Panama", continent: "north-america", flag: countryToFlag("PA") },
  PG: { name: "Papua New Guinea", continent: "oceania", flag: countryToFlag("PG") },
  PY: { name: "Paraguay", continent: "south-america", flag: countryToFlag("PY") },
  PE: { name: "Peru", continent: "south-america", flag: countryToFlag("PE") },
  PH: { name: "Philippines", continent: "asia", flag: countryToFlag("PH") },
  PL: { name: "Poland", continent: "europe", flag: countryToFlag("PL") },
  PT: { name: "Portugal", continent: "europe", flag: countryToFlag("PT") },

  QA: { name: "Qatar", continent: "asia", flag: countryToFlag("QA") },

  RO: { name: "Romania", continent: "europe", flag: countryToFlag("RO") },
  RU: { name: "Russia", continent: "europe", flag: countryToFlag("RU") },
  RW: { name: "Rwanda", continent: "africa", flag: countryToFlag("RW") },

  KN: { name: "Saint Kitts and Nevis", continent: "north-america", flag: countryToFlag("KN") },
  LC: { name: "Saint Lucia", continent: "north-america", flag: countryToFlag("LC") },
  VC: { name: "Saint Vincent and the Grenadines", continent: "north-america", flag: countryToFlag("VC") },
  WS: { name: "Samoa", continent: "oceania", flag: countryToFlag("WS") },
  SM: { name: "San Marino", continent: "europe", flag: countryToFlag("SM") },
  ST: { name: "São Tomé and Príncipe", continent: "africa", flag: countryToFlag("ST") },
  SA: { name: "Saudi Arabia", continent: "asia", flag: countryToFlag("SA") },
  SN: { name: "Senegal", continent: "africa", flag: countryToFlag("SN") },
  RS: { name: "Serbia", continent: "europe", flag: countryToFlag("RS") },
  SC: { name: "Seychelles", continent: "africa", flag: countryToFlag("SC") },
  SL: { name: "Sierra Leone", continent: "africa", flag: countryToFlag("SL") },
  SG: { name: "Singapore", continent: "asia", flag: countryToFlag("SG") },
  SK: { name: "Slovakia", continent: "europe", flag: countryToFlag("SK") },
  SI: { name: "Slovenia", continent: "europe", flag: countryToFlag("SI") },
  SB: { name: "Solomon Islands", continent: "oceania", flag: countryToFlag("SB") },
  SO: { name: "Somalia", continent: "africa", flag: countryToFlag("SO") },
  ZA: { name: "South Africa", continent: "africa", flag: countryToFlag("ZA") },
  KR: { name: "South Korea", continent: "asia", flag: countryToFlag("KR") },
  SS: { name: "South Sudan", continent: "africa", flag: countryToFlag("SS") },
  ES: { name: "Spain", continent: "europe", flag: countryToFlag("ES") },
  LK: { name: "Sri Lanka", continent: "asia", flag: countryToFlag("LK") },
  SD: { name: "Sudan", continent: "africa", flag: countryToFlag("SD") },
  SR: { name: "Suriname", continent: "south-america", flag: countryToFlag("SR") },
  SE: { name: "Sweden", continent: "europe", flag: countryToFlag("SE") },
  CH: { name: "Switzerland", continent: "europe", flag: countryToFlag("CH") },
  SY: { name: "Syria", continent: "asia", flag: countryToFlag("SY") },

  TW: { name: "Taiwan", continent: "asia", flag: countryToFlag("TW") },
  TJ: { name: "Tajikistan", continent: "asia", flag: countryToFlag("TJ") },
  TZ: { name: "Tanzania", continent: "africa", flag: countryToFlag("TZ") },
  TH: { name: "Thailand", continent: "asia", flag: countryToFlag("TH") },
  TL: { name: "Timor-Leste", continent: "asia", flag: countryToFlag("TL") },
  TG: { name: "Togo", continent: "africa", flag: countryToFlag("TG") },
  TO: { name: "Tonga", continent: "oceania", flag: countryToFlag("TO") },
  TT: { name: "Trinidad and Tobago", continent: "north-america", flag: countryToFlag("TT") },
  TN: { name: "Tunisia", continent: "africa", flag: countryToFlag("TN") },
  TR: { name: "Turkey", continent: "asia", flag: countryToFlag("TR") },
  TM: { name: "Turkmenistan", continent: "asia", flag: countryToFlag("TM") },
  TV: { name: "Tuvalu", continent: "oceania", flag: countryToFlag("TV") },

  UG: { name: "Uganda", continent: "africa", flag: countryToFlag("UG") },
  UA: { name: "Ukraine", continent: "europe", flag: countryToFlag("UA") },
  AE: { name: "United Arab Emirates", continent: "asia", flag: countryToFlag("AE") },
  GB: { name: "United Kingdom", continent: "europe", flag: countryToFlag("GB") },
  US: { name: "United States", continent: "north-america", flag: countryToFlag("US") },
  UY: { name: "Uruguay", continent: "south-america", flag: countryToFlag("UY") },
  UZ: { name: "Uzbekistan", continent: "asia", flag: countryToFlag("UZ") },

  VU: { name: "Vanuatu", continent: "oceania", flag: countryToFlag("VU") },
  VA: { name: "Vatican City", continent: "europe", flag: countryToFlag("VA") },
  VE: { name: "Venezuela", continent: "south-america", flag: countryToFlag("VE") },
  VN: { name: "Vietnam", continent: "asia", flag: countryToFlag("VN") },

  YE: { name: "Yemen", continent: "asia", flag: countryToFlag("YE") },
  ZM: { name: "Zambia", continent: "africa", flag: countryToFlag("ZM") },
  ZW: { name: "Zimbabwe", continent: "africa", flag: countryToFlag("ZW") }
};
